from django.urls import path, include
from rest_framework.routers import DefaultRouter

from recipe import views

#def router:a feature of django rest_framework that  automatically generate the URLS for viewset
#when you have viewset, you may have multiple URLs associated with that one viewset
router = DefaultRouter()
#create a new router objects
router.register('tags', views.TagViewSet)
#register our view


app_name = 'recipe'

urlpatterns = [
    path('',include(router.urls))
    ]
    #all of the URLs generated by DefaultRouter will will be included in the URL patterns
